$(document).ready(function(){
  $(".infoWomen").hide();
  $(".infoTrans").hide();
  $(".infoQueer").hide();
  $(".infoAI").hide();

  $("#women").click(function(){
    $(".infoWomen").toggle();
  });
  $("#transwomen").click(function(){
    $(".infoTrans").toggle();
  });
  $("#queers").click(function(){
    $(".infoQueer").toggle();
  });
  $("#AI").click(function(){
    $(".infoAI").toggle();
  });
});
